"""
listing_page.py
Page Object for the Loan account **list** page (Lending Management → All →
Loan account). Sage Intacct labels the list "Loans" (heading), but the module
menu item and Create page both say "loan account" / "loan".

Selectors verified against live DOM 2026-08-17 (release www-p303, LME entity):
  - H1 ...................... "Loans"
  - Create .................. link/button [aria-label="Create"]  (opens "Create loan")
  - Columns ................. BULK_SELECTED, Account number, Account name,
                               Account category, Loan type name, Loan type,
                               Customer, Vendor, Email statements, State,
                               Status, Record number
  - Setup menu link href contains: loan-account.list
"""

from ..listing_page import ListingPage


class LoanAccountListingPage(ListingPage):

    LIST_HEADING = "Loans"
    CREATE_HEADING = "Create loan"
    VIEW_HEADING = "Loan:"
    MODULE_LABEL = "Lending Management"
    HREF_FRAGMENT = "loan-account.list"

    # This list is keyed by Account number / Account name rather than a
    # single "Name" column, so filtering and record lookup are overridden.

    def _account_number_filter(self):
        """The Account number text filter column."""
        return self.frame.locator(
            'input[aria-label="Account number"][placeholder="Contains"]'
        ).first

    def _account_name_filter(self):
        """The Account name text filter column."""
        return self.frame.locator(
            'input[aria-label="Account name"][placeholder="Contains"]'
        ).first

    def search_by_account_number(self, account_number: str):
        box = self._account_number_filter()
        box.fill(account_number)
        box.press("Enter")
        self.page.wait_for_timeout(1_500)

    def search_by_account_name(self, name: str):
        box = self._account_name_filter()
        box.fill(name)
        box.press("Enter")
        self.page.wait_for_timeout(1_500)

    def clear_search(self):
        box = self._account_number_filter()
        box.fill("")
        box.press("Enter")
        self.page.wait_for_timeout(1_000)

    def open_record_by_account_number(self, account_number: str, timeout: int = 15_000):
        """Click a record's Account number link and wait for its View page
        (auto-searches if needed)."""
        link = self.frame.get_by_role("link", name=account_number, exact=True)
        if not link.first.is_visible():
            self.search_by_account_number(account_number)
        link.first.click()
        self.frame.get_by_role("heading", name=self.VIEW_HEADING).wait_for(timeout=timeout)

    def open_record_by_account_name(self, account_name: str, timeout: int = 15_000):
        """
        Click a record's row via its Account name (auto-searches by name if
        needed). Account name is the field tests fully control (unique per
        test); Account number is sometimes auto-generated by the category's
        document sequence and unpredictable, so name is the reliable lookup
        key. The row link itself is still the Account number cell, so this
        filters by name then clicks whatever link is left in the one
        matching row.
        """
        self.search_by_account_name(account_name)
        row = self.frame.locator('[role="row"]').filter(has_text=account_name).first
        row.get_by_role("link").first.click()
        self.frame.get_by_role("heading", name=self.VIEW_HEADING).wait_for(timeout=timeout)

    def is_record_visible(self, account_number: str) -> bool:
        return self.frame.get_by_role("link", name=account_number, exact=True).count() > 0

    def is_record_visible_by_name(self, account_name: str) -> bool:
        return self.frame.locator('[role="row"]').filter(has_text=account_name).count() > 0
